### ISSUE TITLE
benchmark performance

### ISSUE THREAD

**Issue by rom1504** [iejMac/clip-video-encode#2]
clip works best in batch mode
I recommend extracting up to 256 frames at a time and encoding that with clip

**Comment by iejMac** [comment]
Even during inference? I don't see how changing batch size would change the output of a frozen model.

**Comment by rom1504** [comment]
Yes it won't change the output.
I only meant that it's faster to encode several sample at once

**Comment by namhar** [comment]
Often for video what's done is multiclip + multicrop testing. eg. take random n sequence of 16 frames from the video and get m random crops from them. Predict on these m times n sub-videos and ensemble predictions to get final prediction. 

1. Perhaps if want just a sanity check, we can sample only one clip of 16 frames (this is typical but can change based on video encoder) from each test video. this would be the lower bound on performance (1 clip by 1 crop); ensembling should only improve from here. Can get results from a pretrained video model under this condition pretty quickly too.
2. perhaps adding this multi-clip multi-crop embedding to this tool will be useful in future (check out https://github.com/dmlc/decord). Number of embeddings to store would increase for each test video which I am not sure is ok or not.
3. encoding every frame in every video is also interesting, I'm curious to see the level of agreement between all the frames in a given video.
