### ISSUE TITLE
consider supporting streaming / youtube-dl

### ISSUE THREAD

**Issue by rom1504** [iejMac/clip-video-encode#3]
I think it will be really good to support streaming in order to cap the size on disk

**Comment by iejMac** [comment]
Can you say more about what you mean by "streaming"? I'm not exactly sure

**Comment by rom1504** [comment]
Computing clip embeddings from a video stream coming eg from YouTube-dl, without saving the video to disk

**Comment by rom1504** [comment]
I think this will be an important next step
Eg
1. Give tool a list of video IDs
2. Get nice clip embeddings dataset as output with metadata
3. Ready for training and evaluation
