### ISSUE TITLE
use argparse in clip-video-encode

### ISSUE THREAD

**Issue by iejMac** [iejMac/clip-video-encode#36]

**Comment by AbdullahAlfaraj** [comment]
Hi @iejMac, do you intend to replace "fire" with "argparse" ? is this what this issue for?

**Comment by iejMac** [comment]
Hi, I was considering it but now I think it's probably not be worth it. Any thoughts?

@AbdullahAlfaraj

**Comment by AbdullahAlfaraj** [comment]
I'm not sure which choice is better. here is a pull request #47 in case you want to test it.

**Comment by iejMac** [comment]
nice job, thanks. When I get the time I'll check this out

**Comment by iejMac** [comment]
closing this for now, I don't see a reason to do it, haven't had any issues with fire
