### ISSUE TITLE
video reading bottleneck

### ISSUE THREAD

**Issue by iejMac** [iejMac/clip-video-encode#8]
The biggest performance problem is the poor utilization of low frame count to speed up the process. I think video reading FPS (how many samples/s we can read from memory)  should be constant w.r.t. target video FPS (FPS of each video) but this isn't the case. In the below figures I used [clip_video_encode/reader_tests.py](https://github.com/iejMac/clip-video-encode/blob/main/clip_video_encode/reader_tests.py) to compute the reading FPS achieved on a 100 video clip subset of Kinetics700:

<img width="600" alt="Screen Shot 2022-06-15 at 10 36 33 AM" src="https://user-images.githubusercontent.com/61431446/173782512-ae2cf349-8252-450c-9fea-05e15a998b44.png">

<img width="603" alt="Screen Shot 2022-06-15 at 10 38 37 AM" src="https://user-images.githubusercontent.com/61431446/173782988-5dd7eb14-78a3-4578-81b5-4764aaec8b99.png">

Decreasing the number of frames you attempt to process by 25x only about halves your read time. This can probably be improved by using FFmpeg in a more clever way or just tuning the options better. I attempted this but couldn't get this to work well yet.

**Comment by rom1504** [comment]
Is CPU 100% used in this case ?

**Comment by iejMac** [comment]
CPU Usage with FPS = 1
<img width="836" alt="Screen Shot 2022-06-16 at 4 47 47 AM" src="https://user-images.githubusercontent.com/61431446/173980316-efa1118b-570a-4d87-9fd5-22240c5ad920.png">

CPU Usage with FPS = 25
<img width="830" alt="Screen Shot 2022-06-16 at 4 48 39 AM" src="https://user-images.githubusercontent.com/61431446/173980427-868939cd-0ca8-4960-9621-e093833be6ad.png">

**Comment by rom1504** [comment]
Try to run 2 instance at once, just to see what happens

**Comment by iejMac** [comment]
When I run 2 instances they both work and complete just fine but they both go down to 200 samples/s each. CPU usage about doubles. Interesting so each instance slowed down by 20% but cumulatively it got faster by 60%


<img width="834" alt="Screen Shot 2022-06-16 at 5 47 24 AM" src="https://user-images.githubusercontent.com/61431446/173986940-463b715d-b2a0-4a10-b715-7f5e1185b457.png">

**Comment by iejMac** [comment]
3 instances gives you 170 samples/s each = 510 samples/s

**Comment by rom1504** [comment]
Can you check disk usage with iotop?

**Comment by rom1504** [comment]
Try to tune ffmpeg -threads option
Ie increasing the number of threads might achieve the same thing as starting ffmpeg multiple times

**Comment by iejMac** [comment]
Tried tuning -threads already. By rerunning the script and varying -threads from 1 to 90, once again, performance drops off after 10

I'll check iotop once I can get it to work. Currently it throws this error: 
```
OSError: Netlink error: No such file or directory (2)
```
